### ISSUE TITLE
你的小米固件用的感觉怎么样？

### ISSUE THREAD

**Issue by tinysun** [missing233/Xiaomi_BE10000_Prep#1]
杂谈：
我感觉好像讨论日本网络改openwrt的中国人就我们几个。也许各个平台都是我们几个人在讨论。
我就是发现nuro的mape配置的第一人，哈哈。我好像在小红书上看到你出小米路由了1350rmb刷完的。
正题：
你的小米固件用的怎么样？有啥bug没？我在想要不要刷呢。

**Comment by missing233** [comment]
> 杂谈： 我感觉好像讨论日本网络改openwrt的中国人就我们几个。也许各个平台都是我们几个人在讨论。 我就是发现nuro的mape配置的第一人，哈哈。我好像在小红书上看到你出小米路由了1350rmb刷完的。 正题： 你的小米固件用的怎么样？有啥bug没？我在想要不要刷呢。

没什么问题，但是lean的固件一直不更新luci，18.06用的还是太不爽了。后面等BPI-R4的WiFi板子出了再看看选什么
